name: Go Test

on:
  push:
  pull_request:


jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Get dependencies
        run: |
            go get -v -t -d ./...  

      - name: Run Tests
        run: go test ./...
