name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
            Hi there! 👋
            
            Thank you for opening an issue in our open source project. We appreciate your contribution and are here to assist you. Please provide any necessary details or additional information related to the issue, and we'll do our best to address it promptly.
            
            Happy coding! 🚀
        pr-message: |
            Hi there! 👋
            
            Congratulations on creating your first pull request in our open-source project! We're thrilled to have your contribution. Our team will review the changes and provide feedback as soon as possible.
            
            Keep up the great work and feel free to reach out if you have any questions or need further assistance. Happy coding! 🎉
